/**
 * City search over the precomputed GeoNames dump.
 *
 * The file is generated by `npm run build:locations` and committed. No network calls
 * at runtime, same as the holidays. See PLAN.md section 5.
 *
 * STRUCTURE NOTE: this file is not in the list in SETUP.md section 2. It sits in
 * `domain/` for symmetry with `holidays.ts`, which also reads a JSON from `data/` and
 * queries it. Easy to move if you prefer somewhere else.
 *
 * KNOWN LIMITATION: search matches the local name and its ASCII transliteration, not
 * exonyms. "Londres" does not find London and "Ginebra" does not find Genève. Adding
 * them would need the GeoNames alternate names dump, which is two orders of magnitude
 * larger than this one.
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { intlTag, type Locale } from './i18n.js';

/** A city as stored in the JSON. Short keys: the file weighs 3 MB. */
interface RawCity {
  readonly n: string;
  readonly a: string;
  readonly r: string;
  readonly c: string;
  readonly t: string;
  readonly p: number;
}

interface IndexedCity extends RawCity {
  /** Normalized name for comparison: no accents, lowercase. */
  readonly search: string;
}

/** Shape returned by `GET /v1/locations/search`. See PLAN.md section 4. */
export interface Location {
  readonly city: string;
  readonly region: string;
  readonly country: string;
  readonly countryCode: string;
  readonly timezone: string;
}

const DEFAULT_LIMIT = 10;
const MAX_LIMIT = 25;

let index: IndexedCity[] | null = null;

/**
 * Searches cities by prefix.
 *
 * Names that start with what was typed rank above names that merely contain it, and
 * within each group the order is by population. Typing "san" should surface São Paulo
 * before a namesake town of fifteen thousand people.
 *
 * A query shorter than two characters returns nothing: with a single letter the result
 * is noise, and walking 34 thousand cities buys nothing.
 *
 * The country name comes back in the caller's locale; city and region names stay in
 * their local spelling, which is how GeoNames stores them.
 */
export function searchCities(
  query: string,
  locale: Locale,
  limit = DEFAULT_LIMIT,
): Location[] {
  const term = normalize(query);
  if (term.length < 2) return [];

  const cap = Math.min(Math.max(1, Math.trunc(limit) || DEFAULT_LIMIT), MAX_LIMIT);
  const prefixMatches: IndexedCity[] = [];
  const containsMatches: IndexedCity[] = [];

  for (const city of load()) {
    const isPrefix = city.search.startsWith(term);
    if (isPrefix) prefixMatches.push(city);
    // The index is sorted by population, so once there are `cap` prefix matches
    // nothing better can show up further down.
    if (prefixMatches.length >= cap) break;
    if (isPrefix) continue;
    if (containsMatches.length >= cap) continue;
    if (!city.search.includes(term)) continue;
    containsMatches.push(city);
  }

  const names = new Intl.DisplayNames([intlTag(locale)], { type: 'region' });
  return [...prefixMatches, ...containsMatches]
    .slice(0, cap)
    .map((city) => toLocation(city, names));
}

/** Clears the cache. Tests only. */
export function resetCache(): void {
  index = null;
}

export function cityCount(): number {
  return load().length;
}

function toLocation(city: IndexedCity, names: Intl.DisplayNames): Location {
  return {
    city: city.n,
    region: city.r,
    country: countryName(city.c, names),
    countryCode: city.c,
    timezone: city.t,
  };
}

/**
 * Strips accents and lowercases.
 *
 * NFD splits a letter from its diacritic and the combining range removes the loose
 * marks, so "Bogotá" and "bogota" compare equal. It leaves non-Latin scripts alone:
 * those are covered by the GeoNames `asciiname`, already transliterated.
 */
function normalize(text: string): string {
  return text
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .trim()
    .replace(/\s+/g, ' ');
}

function load(): IndexedCity[] {
  if (index) return index;

  const path = join(packageRoot(), 'src', 'data', 'locations', 'cities.json');
  const raw = readCities(path);
  index = raw.map((city) => ({
    ...city,
    // The ASCII name is what lets you type "Zurich" and find Zürich.
    search: normalize(city.a || city.n),
  }));
  return index;
}

function readCities(path: string): RawCity[] {
  try {
    return (JSON.parse(readFileSync(path, 'utf8')) as { cities: RawCity[] }).cities;
  } catch {
    // Without the dump there is no autocomplete, but the rest of the backend works.
    return [];
  }
}

function countryName(countryCode: string, names: Intl.DisplayNames): string {
  try {
    return names.of(countryCode) ?? countryCode;
  } catch {
    return countryCode;
  }
}

function packageRoot(): string {
  let current = dirname(fileURLToPath(import.meta.url));
  for (let i = 0; i < 6; i++) {
    try {
      readFileSync(join(current, 'package.json'), 'utf8');
      return current;
    } catch {
      current = dirname(current);
    }
  }
  throw new Error('Could not find the package root');
}
